### PR TITLE
feat(doc): Update the governance documentation

### PR DESCRIPTION
**Pull request by leonrayang**
### Motivation

feat(doc): Update the governance documentationa
- Clearify the promotion and exit rules for committers.
- Add the Expectations for maintainer and committers
- Clearify the core maintainers

### Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Documentation Update (if none of the other choices apply)
- [ ] So on...

### Verifying this change

- [x] Make sure that the change passes the testing checks.

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *This can be verified in development debugging*
  - *This can be realized in a mocked environment, like a test cluster consisting in docker*

*(or)*

This change `MUST` reappear in online clusters, or occur in that specific scenarios.

### Does this pull request potentially affect one of the following parts:

- [ ] Master
- [ ] MetaNode
- [ ] DataNode
- [ ] ObjectNode
- [ ] AuthNode
- [ ] LcNode
- [ ] Blobstore
- [ ] Client
- [ ] Cli
- [ ] SDK
- [ ] Other Tools
- [ ] Common Packages
- [ ] Dependencies
- [ ] Anything that affects deployment

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Review Expection

- [ ] `in-two-days`
- [x] `weekly`
- [ ] `free-time`
- [ ] `whenever`

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by Cloudstriff — APPROVED** [review]
+1

**Comment by cessory** [comment]
+1

**Comment by sejust** [comment]
+1

**Review by sejust — APPROVED** [review]

**Comment by Victor1319** [comment]
+1

**Review by Victor1319 — APPROVED** [review]

**Review by mervinkid — APPROVED** [review]
+1

**Comment by hooklee2000** [comment]
+1

**Review by awzhgw — APPROVED** [review]
+1

**Review by xiaochunhe — APPROVED** [review]
+1

**Comment by leonrayang** [comment]
+1

**Review by bboyCH4 — APPROVED** [review]

**Comment by leonrayang** [comment]
@all， Originally, this PR was supposed to be displayed for two weeks according to the governance document, but it was merged due to an operational error. Fortunately, the votes met the merging conditions. Moving forward, we will emphasize this in the community and do not plan to implement any mechanisms to restrict who can merge PRs.

**Pull request merged**
