### PR TITLE
Update api_service.go

### PR DESCRIPTION
**Pull request by guoguodan**
edit error words : sucess -> "success"

### CODE REVIEW

**Comment by sejust** [comment]
@guoguodan  hi, edit your commit with signoff.

**Review by sejust — APPROVED** [review]

**Review by leonrayang — APPROVED** [review]
LGTM

**Review by leonrayang — COMMENTED** [review]
Commit sha: [2b8a6a5](https://github.com/cubefs/cubefs/pull/2821/commits/2b8a6a5bdab058926afdf7320bee3df014683ccb), Author: guoguodan, Committer: 梁曟風; The sign-off is missing.

**Comment by leonrayang** [comment]
@guoguodan Commit sha: [2b8a6a5](https://github.com/cubefs/cubefs/pull/2821/commits/2b8a6a5bdab058926afdf7320bee3df014683ccb), Author: guoguodan, Committer: 梁曟風; The sign-off is missing.  需要补充下signoff信息

**Comment by sejust** [comment]
move to #2954

**Pull request closed without merging**
