### PR TITLE
FIX: fix the metrics of volume space

### PR DESCRIPTION
**Pull request by liubingxing**
Signed-off-by: liubingxing <liubbingxing@gmail.com>

we create a volume with 10000GB, but the metrics show the wrong result.
image

image

The volume metrics: **cfs_master_vol_total_GB** and **cfs_master_vol_used_GB** use **volStatInfo.TotalSize** which count by **bytes**.
We should fix the metrics by **volStatInfo.TotalSize/util.GB**

### CODE REVIEW

**Comment by leonrayang** [comment]
cli volume info use master's vol.Capacity directly and should not need to divide by GB

**Comment by liubingxing** [comment]
@leonrayang The cli volume info is right, but the volume info from http metrics need to fix.

**Review by Victor1319 — DISMISSED** [review]

**Comment by Victor1319** [comment]
merge  after grafana dashboard template json file also be updated, to avoid users confused when using metrics monitor

**Comment by leonrayang** [comment]
> merge after grafana dashboard template json file also be updated, to avoid users confused when using metrics monitor

ok

**Comment by true1064** [comment]
@liubingxing please resolve the confilicts

**Review by sejust — APPROVED** [review]

**Comment by sejust** [comment]
move to #2800

**Pull request closed without merging**
