### PR TITLE
feat(doc): Add Shuqiang Zheng to be a committer.

### PR DESCRIPTION
**Pull request by shuqiang-zheng**
Fixes: no

Main Issue: no

### Motivation

I contributed a lot of code to the CubeFS. In the meantime, I've reviewed at a lot of PRs too. I want to add myself(Shuqiang Zheng) as a committer to do more things.

In the future, I would first like to see the project code improve stability and security by continuously optimizing legacy issues. Then I will consider improving its performance and scalability, for example by providing support for rdma to improve communication performance.

This year, I'm also looking forward to more areas of progress with CubeFS.

PRs: https://github.com/cubefs/cubefs/pulls?page=1&q=is%3Apr+author%3Ashuqiang-zheng
Reviews: https://github.com/pulls?q=is%3Apr+reviewed-by%3Ashuqiang-zheng+is%3Aclosed

### Modifications

``` text
Update the maintainers documentation.
```

### Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Documentation Update (if none of the other choices apply)
- [ ] So on...

### Verifying this change

- [ ] Make sure that the change passes the testing checks.

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *This can be verified in development debugging*
  - *This can be realized in a mocked environment, like a test cluster consisting in docker*

*(or)*

This change `MUST` reappear in online clusters, or occur in that specific scenarios.

### Does this pull request potentially affect one of the following parts:

- [ ] Master
- [ ] MetaNode
- [ ] DataNode
- [ ] ObjectNode
- [ ] AuthNode
- [ ] LcNode
- [ ] Blobstore
- [ ] Client
- [ ] Cli
- [ ] SDK
- [ ] Other Tools
- [ ] Common Packages
- [ ] Dependencies
- [ ] Anything that affects deployment

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Review Expection

- [ ] `in-two-days`
- [x] `weekly`
- [ ] `free-time`
- [ ] `whenever`

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by leonrayang — APPROVED** [review]
LGTM

**Comment by leonrayang** [comment]
+1

**Review by mervinkid — APPROVED** [review]
Approve +1

**Comment by bladehliu** [comment]
+1

**Review by xiaochunhe — COMMENTED** [review]
+1

**Review by awzhgw — COMMENTED** [review]
+1

**Pull request merged**
