### PR TITLE
[Feature]: CI tests support run on podman

### PR DESCRIPTION
**Pull request by NaturalSelect**
**What this PR does / why we need it**:

* Support run CI test on podman.

**Which issue this PR fixes**:

fixes #

**Special notes for your reviewer**:

* It is better to change nginx ports to `8080`(or any >= 1024 port).

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by sejust** [comment]
Can you work on the pr #2973 ？

**Comment by NaturalSelect** [comment]
> Can you work on the pr #2973 ？

Do you mean change base branch to #2973?

**Comment by sejust** [comment]
> > Can you work on the pr #2973 ？
> 
> Do you mean change base branch to #2973?

 support podman based on branch `docker-yml` and merge all to master in the PR.

**Comment by NaturalSelect** [comment]
> > > Can you work on the pr #2973 ？
> > 
> > 
> > Do you mean change base branch to #2973?
> 
> support podman based on branch `docker-yml` and merge all to master in the PR.

OK, let me do it.

**Comment by NaturalSelect** [comment]
@sejust Please review again.

**Comment by NaturalSelect** [comment]
Maybe we should enable CI tests for `docker-yml` branch?

**Comment by sejust** [comment]
> Maybe we should enable CI tests for `docker-yml` branch?

sorry，I have force updated branch `docker-yml`, Rebase on it then merge to master.

**Comment by NaturalSelect** [comment]
> > Maybe we should enable CI tests for `docker-yml` branch?
> 
> sorry，I have force updated branch `docker-yml`, Rebase on it then merge to master.

Done.

**Pull request merged**
