### PR TITLE
[Enhancement]: Support reporting the total size of writable space in …

### LINKED ISSUE #2658: [Enhancement]: Support reporting the total size of writable space in the cluster.
### Contact Details

_No response_

### Is there an existing issue for this?

- [X] I have searched all the existing issues

### What would you like to be added?

Support only calculating the total size of writable space in the cluster.

### Why is this needed?

The current total size includes the size of non-writable nodes, making it difficult to accurately assess the available size of the cluster

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by morphes1995**
**What this PR does / why we need it**:

**Which issue this PR fixes**:

fixes #2658 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Review by leonrayang — APPROVED** [review]
LGTM

**Review by sejust — APPROVED** [review]

**Comment by leonrayang** [comment]
@morphes1995 There are protocol compatibility issues here 
`
func (api *AdminAPI) GetCluster() (cv *proto.ClusterView, err error) {
	var buf []byte

	request := newAPIRequest(http.MethodGet, proto.AdminGetCluster)
	if buf, err = api.mc.serveRequest(request); err != nil {
		return
	}

	cv = &proto.ClusterView{}
	if err = json.Unmarshal(buf, &cv); err != nil {
		return
	}

	return
}
`

**Comment by leonrayang** [comment]
@morphes1995 There is no problem with the new fields of NodeStatInfo, but other fields need to be restored. Or you support a new protocol separately, so that the old interface service still supports it

**Comment by leonrayang** [comment]
I need revert first now，please push it again once finish the modifcation

**Comment by morphes1995** [comment]
> I need revert first now，please push it again once finish the modifcation

ok ,wait a moment

**Comment by morphes1995** [comment]
> I need revert first now，please push it again once finish the modifcation

fixed!  https://github.com/cubefs/cubefs/pull/3033

**Pull request merged**
