### PR TITLE
chore: update MAINTAINERS.md

### PR DESCRIPTION
**Pull request by setcy**
**What this PR does / why we need it**:

Add commiter
See https://mp.weixin.qq.com/s/m5lfzInds7I7v_k-k_6r_Q

### CODE REVIEW

**Review by xiaochunhe — DISMISSED** [review]

**Review by leonrayang — DISMISSED** [review]
LGTM

**Comment by leonrayang** [comment]
@setcy please resolve the conflicts,thanks

**Comment by setcy** [comment]
> @setcy please resolve the conflicts,thanks

Done.

**Review by sejust — DISMISSED** [review]

**Comment by sejust** [comment]
@setcy   Using markdown's  `reference-style link`  on `Organization` will be better.

**Review by sejust — APPROVED** [review]

**Review by Victor1319 — APPROVED** [review]
LGTM

**Pull request merged**
