### PR TITLE
feat(docs): optimize illustrations for documents in Zone Management

### PR DESCRIPTION
**Pull request by setcy**
close: #2024

**What this PR does / why we need it**:

There are errors in the image of the Zone Management chapter, this pr is going to correct it.

### CODE REVIEW

**Comment by pengtianyue025** [comment]
@Victor1319 @bboyCH4 please review this.

**Comment by bboyCH4** [comment]
thanks for your contribution

**Review by bboyCH4 — APPROVED** [review]

**Review by pengtianyue025 — APPROVED** [review]
LGTM

**Comment by xiaochunhe** [comment]
:smile: good job，the new diagram expresses much more clearly～

**Pull request merged**
