### PR TITLE
Release docker image for arm64

### PR DESCRIPTION
**Pull request by odidev**
The following file has been modified:
Modified file .github/workflows/ci.yml to build and push the image for both amd64 and arm64 platforms.

Signed-off-by: odidev odidev@puresoftware.com

### CODE REVIEW

**Comment by hooklee2000** [comment]
LGTM. @mervinkid  please approve running workflows.

**Comment by leonrayang** [comment]
@odidev Some checks were not successful

**Comment by hooklee2000** [comment]
Follow Settings => Secrets => New repository secret , we need create DOCKER_TOKEN as docker password.

**Comment by odidev** [comment]
> @odidev Some checks were not successful

@leonrayang 

Publish job is failing as you need to generate token for your own docker repository and store it as secret key in Github Actions. Please refer the following document to generate the token -https://docs.docker.com/ci-cd/github-actions/#:~:text=Add%20your%20Docker%20ID%20as,Personal%20Access%20Token%20(PAT). 

 

The LTP test which is failing here, is passing on my Github actions. For more details, please check [here](https://github.com/odidev/cubefs/actions/runs/2494207370). 

It looks like the test result is not consistent and I think failures are not related to these changes.

**Comment by leonrayang** [comment]
> > @odidev Some checks were not successful
> 
> @leonrayang
> 
> Publish job is failing as you need to generate token for your own docker repository and store it as secret key in Github Actions. Please refer the following document to generate the token -https://docs.docker.com/ci-cd/github-actions/#:~:text=Add%20your%20Docker%20ID%20as,Personal%20Access%20Token%20(PAT).
> 
> The LTP test which is failing here, is passing on my Github actions. For more details, please check [here](https://github.com/odidev/cubefs/actions/runs/2494207370).
> 
> It looks like the test result is not consistent and I think failures are not related to these changes.

I see, the pr will be managed by mervin who familiar with the process

**Comment by odidev** [comment]
Hi team,

Can you please review this PR and let me know if any changes is required.

**Comment by leonrayang** [comment]
> Hi team,
> 
> Can you please review this PR and let me know if any changes is required.

@mervinkid  please help to review this pr, thank you.

**Comment by true1064** [comment]
@odidev please resolve the conflicts

**Pull request closed without merging**
