### PR TITLE
fix sdk compilation

### LINKED ISSUE #2500: [Enhancement]: Some problems encountered during the integration of cubefs sdk into clickhouse cmake compilation
### Contact Details

_No response_

### Is there an existing issue for this?

- [X] I have searched all the existing issues

### What would you like to be added?

1. Generate sdk static library file
2. The naming format of variables does not meet the requirements of gcc 4.9+ ( xxx is reserved because it starts with '_' followed by a capital letter [-Werror,-Wreserved-identifier])

### Why is this needed?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by RunningXie**
**What this PR does / why we need it**:
1. Generate sdk static library file
2.  Fix the naming format of variables to meet the requirements of gcc 4.9+ ( xxx is reserved because it starts with '_' followed by a capital letter [-Werror,-Wreserved-identifier])

**Which issue this PR fixes**:

fixes #2500

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by setcy** [comment]
1. please fix [dco error](https://github.com/cubefs/cubefs/pull/2501/checks?check_run_id=15934917376) first.
2. the [libsdk/libcfs.h](https://github.com/cubefs/cubefs/pull/2501/files#diff-48e1897e56d3aa34652ee18183a3468dce6b1b0c03e7080e5a014f8f380eca0e) file seems is a generated file, maybe it's not a good idea to edit this file manually?

**Comment by RunningXie** [comment]
Hope to fix these compilation error：
1. cgo-gcc-export-header-prolog:25:14: error: identifier '_check_for_64_bit_pointer_matching_GoInt' is reserved because it starts with '_' at global scope [-Werror,-Wreserved-identifier]
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];
             ^
2. libsdk.go:19:9: error: '_GNU_SOURCE' macro redefined [-Werror,-Wmacro-redefined]
#define _GNU_SOURCE
        ^
<built-in>:430:9: note: previous definition is here
#define _GNU_SOURCE 1
        ^
3. cgo-builtin-export-prolog:8:48: error: identifier '_GoString_' is reserved because it starts with '_' followed by a capital letter [-Werror,-Wreserved-identifier]
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
                                               ^

**Comment by RunningXie** [comment]
> Hope to fix these compilation error：
> 
> 1. cgo-gcc-export-header-prolog:25:14: error: identifier '_check_for_64_bit_pointer_matching_GoInt' is reserved because it starts with '_' at global scope [-Werror,-Wreserved-identifier]
>    typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];
>    ^
> 2. libsdk.go:19:9: error: '_GNU_SOURCE' macro redefined [-Werror,-Wmacro-redefined]
>    #define _GNU_SOURCE
>    ^
>    :430:9: note: previous definition is here
>    #define _GNU_SOURCE 1
>    ^
> 3. cgo-builtin-export-prolog:8:48: error: identifier '_GoString_' is reserved because it starts with '_' followed by a capital letter [-Werror,-Wreserved-identifier]
>    typedef struct { const char *p; ptrdiff_t n; } _GoString_;
>    ^

The reason for the problem is that there are reserved-identifier and macro-redefined errors in the header file.
To solve this problem, I use cmake to automatically add #pragma GCC diagnostic push/pop into the header file before compiling. In this way, these two types of errors can be masked.

**Comment by baijiaruo** [comment]
Didn’t fetch the latest code before merging and rebase？ @RunningXie

**Pull request closed without merging**
