### PR TITLE
Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by koyohara**
**What this PR does / why we need it**:

**Which issue this PR fixes**:

fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Review by xiaochunhe — APPROVED** [review]
LGTM

**Comment by leonrayang** [comment]
reopen

**Comment by leonrayang** [comment]
reopen

**Comment by leonrayang** [comment]
reopen

**Comment by leonrayang** [comment]
reopen

**Comment by true1064** [comment]
the commit is already merge by another pr #2596.
so close this pr.

**Pull request closed without merging**
