### PR TITLE
feat(doc): Update the Governance Document

### PR DESCRIPTION
**Pull request by leonrayang**
### Motivation

The description of "project lead" implies a somewhat authoritarian role, but with the establishment of a steering committee, the steering committee should be considered the highest decision-making body.

### Modifications

Canceling the position of "project lead," the steering committee has the authority to decide on the majority of matters. By voting through the steering committee, disputes can be resolved completely, eliminating the need for a project lead.

### Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Documentation Update (if none of the other choices apply)
- [ ] So on...

### Verifying this change

- [ ] Make sure that the change passes the testing checks.

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *This can be verified in development debugging*
  - *This can be realized in a mocked environment, like a test cluster consisting in docker*

*(or)*

This change `MUST` reappear in online clusters, or occur in that specific scenarios.

### Does this pull request potentially affect one of the following parts:

- [ ] Master
- [ ] MetaNode
- [ ] DataNode
- [ ] ObjectNode
- [ ] AuthNode
- [ ] LcNode
- [ ] Blobstore
- [ ] Client
- [ ] Cli
- [ ] SDK
- [ ] Other Tools
- [ ] Common Packages
- [ ] Dependencies
- [ ] Anything that affects deployment

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Review Expection

- [ ] `in-two-days`
- [x] `weekly`
- [ ] `free-time`
- [ ] `whenever`

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by Victor1319 — APPROVED** [review]
LGTM

**Comment by cessory** [comment]
+1

**Comment by Victor1319** [comment]
+1

**Comment by Cloudstriff** [comment]
+1

**Comment by leonrayang** [comment]
+1

**Comment by sejust** [comment]
+1

**Review by xiaochunhe — APPROVED** [review]
+1

**Review by mervinkid — APPROVED** [review]
Approve +1

**Comment by bladehliu** [comment]
+1

**Pull request merged**
