### PR TITLE
docs(tools): split `Using CLI Tools` section

### PR DESCRIPTION
**Pull request by setcy**
**What this PR does / why we need it**:

It appears that the [Using CLI Tools](https://cubefs.io/docs/master/maintenance/tool.html) section contains an excessive amount of content. To optimize its presentation, I suggest splitting it into several files for better organization and readability. 

**Special notes for your reviewer**:

- This PR does not add a lot of content, most of the content is provided as it is, only the layout is modified.
- I removed the `cfs-cli completion command` as it doesn't appear to be available currently.

### CODE REVIEW

**Review by xiaochunhe — DISMISSED** [review]
the layout is more concise and clear

**Review by xiangcai1215 — DISMISSED** [review]
LGTM

**Review by true1064 — APPROVED** [review]
LGTM

**Review by true1064 — APPROVED** [review]
LGTM

**Review by xiangcai1215 — APPROVED** [review]

**Pull request merged**
