### PR TITLE
[Enhancement] add authentication for master admin api

### PR DESCRIPTION
**Pull request by M1eyu2018**
Currently, the config of the fuse client has the master address, and some body can send http requests to the master through this address, including deleting mp/dp whitout permission control.

We should add more permission control to the following http requests which can manage cluster:
//Master API cluster management
proto.AdminClusterFreeze
proto.AddRaftNode
proto.RemoveRaftNode
proto.AdminSetNodeInfo
proto.AdminSetNodeRdOnly

// Master API volume management
proto.AdminCreateVol
proto.AdminDeleteVol
proto.AdminUpdateVol
proto.AdminVolShrink
proto.AdminVolExpand

// Master API meta partition management
proto.AdminLoadMetaPartition
proto.AdminDecommissionMetaPartition
proto.AdminChangeMetaPartitionLeader
proto.AdminCreateMetaPartition
proto.AdminAddMetaReplica
proto.AdminDeleteMetaReplica
proto.QosUpdate
proto.QosUpdateZoneLimit
proto.QosUpdateMasterLimit
proto.QosUpdateClientParam

// Master API data partition management
proto.AdminCreateDataPartition
proto.AdminDataPartitionChangeLeader
proto.AdminLoadDataPartition
proto.AdminDecommissionDataPartition
proto.AdminAddDataReplica
proto.AdminDeleteDataReplica
proto.AdminSetDpRdOnly

// Master API meta node management
proto.AddMetaNode
proto.DecommissionMetaNode
proto.MigrateMetaNode
proto.AdminSetMetaNodeThreshold
proto.AdminUpdateMetaNode

// Master API data node management
proto.AddDataNode
proto.DecommissionDataNode
proto.MigrateDataNode
proto.CancelDecommissionDataNode
proto.DecommissionDisk
proto.AdminUpdateNodeSetCapcity
proto.AdminUpdateNodeSetId
proto.AdminUpdateDomainDataUseRatio
proto.AdminUpdateZoneExcludeRatio
proto.RecommissionDisk

// Master API user management
proto.UserCreate
proto.UserDelete
proto.UserUpdate
proto.UserUpdatePolicy
proto.UserRemovePolicy
proto.UserDeleteVolPolicy
proto.UserTransferVol

// Master API zone management
proto.UpdateZone

Base on the origin auth node framework, the authentication process is represented below.
authentication_process

### CODE REVIEW

**Comment by leonrayang** [comment]
@M1eyu2018 Does the check is configurable,the online environment may not have the authnode

**Comment by M1eyu2018** [comment]
> @M1eyu2018 Does the check is configurable,the online environment may not have the authnode

Yes, config is in master. If authenticate is true,  interceptor which checks authentication will work. @leonrayang 
image

**Comment by leonrayang** [comment]
@M1eyu2018 please resolve the conflicts,thank you.

**Comment by M1eyu2018** [comment]
> @M1eyu2018 please resolve the conflicts,thank you.

@leonrayang done

**Comment by true1064** [comment]
@M1eyu2018 please resolve the conflicts

**Review by leonrayang — APPROVED** [review]
LGTM

**Review by true1064 — APPROVED** [review]
LGTM

**Comment by Zorlin** [comment]
This has been merged 6+ months ago - can we get it into a CubeFS release for usage please? :)

**Pull request merged**
