### PR TITLE
feat(port): support multiple datanode/metanode instances using dif…

### PR DESCRIPTION
**Pull request by zhang111feng**
…ferent port on a single node

**What this PR does / why we need it**:
Support multiple datanode/metanode instances using different port on a single node.In the previous version, every datanode or metanode in the same raft group is required to be configured with the same raftHeartBeatPort and replicaPort because each node splices ports of peers through its own port.
**Which issue this PR fixes**:

fixes https://github.com/cubefs/cubefs/issues/3004

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by Victor1319** [comment]
It's a really good and big job, and maybe you should consider the process of upgrading an old cluster because the default values for `raftport` and `replica port` are 0 when the older nodes were registered. This could potentially cause issues.

**Comment by zhang111feng** [comment]
> It's a really good and big job, and maybe you should consider the process of upgrading an old cluster because the default values for `raftport` and `replica port` are 0 when the older nodes were registered. This could potentially cause issues.

I have made some attempts to resolve the compatibility issues when upgrading the old version.I have finished the dataNode part, but I think it still have problems.I think I need some help and suggestions for improvement.

**Comment by zhang111feng** [comment]
The problem I encounter now is that after dataNodes are restarted one by one, although the META information in the locally stored dp file can be updated to the new version with port information, the META information may not be correctly changed when other member changes such as del-replica are performed.

**Comment by zhang111feng** [comment]
I found that in the branch &lt;develop-hybridcloud-lifecycle&gt;, the branch also changes the structure of dataNode with adding `mediaType` when it adds the storage tiering function. How does that solve the problem in the process of upgrading an old cluster?

**Comment by zhang111feng** [comment]
I think the problem mentioned doesn't exist anymore, but I'm not sure if there are other problems because I haven't fully understood the mechanism here.

**Comment by true1064** [comment]
> The problem I encounter now is that after dataNodes are restarted one by one, although the META information in the locally stored dp file can be updated to the new version with port information, the META information may not be correctly changed when other member changes such as del-replica are performed.

**Comment by true1064** [comment]
> I found that in the branch <develop-hybridcloud-lifecycle>, the branch also changes the structure of dataNode with adding `mediaType` when it adds the storage tiering function. How does that solve the problem in the process of upgrading an old cluster?
 in branch <develop-hybridcloud-lifecycle>,  filed  `mediaType` is only on the master, there no filed added on datanode

**Pull request closed without merging**
