### PR TITLE
fix(depends): fix slice init length

### PR DESCRIPTION
**Pull request by cuishuang**
The intention here should be to initialize a slice with a capacity of len(s.raftFsm.replicas) rather than initializing the length of this slice.

Main Issue: #xyz

### Motivation

blaaaaa

### Modifications

``` text
blaaaaa
```

### Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] So on...

### Verifying this change

- [ ] Make sure that the change passes the testing checks.

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *This can be verified in development debugging*
  - *This can be realized in a mocked environment, like a test cluster consisting in docker*

*(or)*

This change `MUST` reappear in online clusters, or occur in that specific scenarios.

### Does this pull request potentially affect one of the following parts:

- [ ] Master
- [ ] MetaNode
- [ ] DataNode
- [ ] ObjectNode
- [ ] AuthNode
- [ ] LcNode
- [ ] Blobstore
- [ ] Client
- [ ] Cli
- [ ] SDK
- [ ] Other Tools
- [ ] Common Packages
- [ ] Dependencies
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Review Expection

- [ ] `in-two-days`
- [ ] `weekly`
- [ ] `free-time`
- [x] `whenever`

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by leonrayang** [comment]
@cuishuang I am a little confused. The code make([]proto.Peer, len(s.raftFsm.replicas)) indicates that the size of the slice is known before initialization. This seems reasonable. Could you provide more details?Why is dynamic initialization needed?

**Comment by cuishuang** [comment]
> @cuishuang I am a little confused. The code make([]proto.Peer, len(s.raftFsm.replicas)) indicates that the size of the slice is known before initialization. This seems reasonable. Could you provide more details?Why is dynamic initialization needed?

Of course.  You can see the online demo and will understand immedially.

 https://go.dev/play/p/q1BcVCmvidW
 
Thanks for your review.

**Comment by leonrayang** [comment]
> > @cuishuang I am a little confused. The code make([]proto.Peer, len(s.raftFsm.replicas)) indicates that the size of the slice is known before initialization. This seems reasonable. Could you provide more details?Why is dynamic initialization needed?
> 
> Of course. You can see the online demo and will understand immedially.
> 
> https://go.dev/play/p/q1BcVCmvidW
> 
> Thanks for your review.

Excatlly yes，thank you！

**Review by Victor1319 — APPROVED** [review]
LGTM

**Review by bboyCH4 — APPROVED** [review]

**Comment by leonrayang** [comment]
@cuishuang This pull request can be closed, I will cherry-pick this to our local repository, and will publish it in the 3.4.0 version with your author name.

**Comment by cuishuang** [comment]
> @cuishuang This pull request can be closed, I will cherry-pick this to our local repository, and will publish it in the 3.4.0 version with your author name.

Thanks!

**Comment by cuishuang** [comment]
I will close this PR.

**Pull request closed without merging**
