### PR TITLE
test(ci): show more information in CI to help debug

### PR DESCRIPTION
**Pull request by NaturalSelect**
**What this PR does / why we need it**:

* Show more information in CI to help debug.
* Fix dp count limit.
* Fix `metanode info` cli.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by NaturalSelect** [comment]
The reason why scenario test fail is unit test use too much disk space, [the CI result of this pull request](https://github.com/cubefs/cubefs/actions/runs/5529202750/jobs/10086941496?pr=2278) proof this.

It [passed](https://github.com/cubefs/cubefs/actions/runs/5529010272/jobs/10086488742), when I modify `run_docker.sh` to skip unit test.

**Review by leonrayang — DISMISSED** [review]
LGTM

**Comment by NaturalSelect** [comment]
Please run all failed CI tests after merge this pull request.

**Review by Victor1319 — DISMISSED** [review]
LGTM

**Comment by NaturalSelect** [comment]
Move to #2300

**Pull request closed without merging**
